name: Build and Release
run-name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-job:
    name: Build scheduler-plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go version
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Install versioning tool
        run: go install github.com/xchapter7x/versioning@latest
      - name: Determine Version
        id: determine_version
        run: |
          echo VERSION=$(~/go/bin/versioning bump_patch) >> ${GITHUB_ENV}
      - name: Build scheduler-plugin
        env:
          COMMIT: ${{ github.sha }}
        run: .github/scripts/build.sh
      - name: upload scheduler-plugin
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  release_job:
    name: Release scheduler-plugin
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install versioning tool
        run: go install github.com/xchapter7x/versioning@latest
      - name: Determine Version
        id: determine_version
        run: |
          echo VERSION=$(~/go/bin/versioning bump_patch) >> ${GITHUB_ENV}
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Create Release using hub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          asset_file_list=()
          for f in dist/*
          do
            asset_file_list+=("-a" "${f}")
          done
          tag_name=${VERSION}
          hub release create "${asset_file_list[@]}" -m "Release $tag_name" "$tag_name"
          

